project_id = "paokcsxuxipnbnbgnlzs"

[functions.backend-api]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.risecheckout-webhook]
verify_jwt = false
